# Generated by Django 5.0.14 on 2026-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('product_create', 'Product Created'), ('product_edit', 'Product Edited'), ('product_delete', 'Product Deleted'), ('order_status_update', 'Order Status Updated'), ('staff_create', 'Staff Account Created'), ('staff_edit', 'Staff Account Edited'), ('staff_deactivate', 'Staff Account Deactivated'), ('staff_activate', 'Staff Account Activated'), ('stock_validation_failed', 'Stock Validation Failed'), ('per_product_limit_failed', 'Per-Product Limit Failed'), ('cart_capacity_failed', 'Cart Capacity Failed'), ('order_cooldown_failed', 'Order Cooldown Failed'), ('daily_order_limit_failed', 'Daily Order Limit Failed'), ('cart_add_error', 'Cart Add Error')], max_length=30),
        ),
    ]
