# Generated by Django 5.0.14 on 2026-06-14 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='city',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='housenumber',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='streetname',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('product_create', 'Product Created'), ('product_edit', 'Product Edited'), ('product_delete', 'Product Deleted'), ('order_status_update', 'Order Status Updated'), ('staff_create', 'Staff Account Created'), ('staff_edit', 'Staff Account Edited'), ('staff_deactivate', 'Staff Account Deactivated'), ('staff_activate', 'Staff Account Activated'), ('stock_validation_failed', 'Stock Validation Failed'), ('per_product_limit_failed', 'Per-Product Limit Failed'), ('cart_capacity_failed', 'Cart Capacity Failed'), ('order_cooldown_failed', 'Order Cooldown Failed'), ('daily_order_limit_failed', 'Daily Order Limit Failed'), ('cart_add_error', 'Cart Add Error'), ('order_created', 'Order Created'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_verification_failed', 'Payment Verification Failed'), ('pickup_completed', 'Pickup Completed')], max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymongo_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paymongo_checkout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bakery.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
