# Generated by Django 5.0.14 on 2026-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_remove_receipt_barangay_remove_receipt_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pickup_date',
            new_name='pickup_availability_date',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='pickup_date',
            new_name='pickup_availability_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
