# Generated by Django on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0014_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
    ]
