# Generated by Django 4.2.30 on 2026-06-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0016_fix_reference_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_set_password',
            field=models.BooleanField(default=False, help_text='Whether user has set their own password (for staff accounts)'),
        ),
    ]
