# Generated by Django 4.2.30 on 2026-06-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0017_add_totp_secret'),
        ('bakery', '0017_userprofile_has_set_password'),
    ]

    operations = [
    ]
